"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
import glob
from setuptools import setup

APP = ['main.py']
APP_NAME = "PacMan"
APP_VERSION = "0.1.0 alpha"

setup_dir = os.path.dirname(os.path.abspath(__file__))
icon_files = glob.glob(os.path.join(setup_dir,'icons/*'))
yaml_files = glob.glob(os.path.join(setup_dir,'config/*'))
fonts = glob.glob(os.path.join(setup_dir,'fonts/*'))
DATA_FILES = [
    ('icons', icon_files),
    ('config', yaml_files),
    ('fonts', fonts)
]
OPTIONS = {
    'packages': ['PyQt6', 'bs4', 'yaml'],
    # 'excludes': ['wheel'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleVersion': APP_VERSION,
        'CFBundleIdentifier': f'com.vaishnav.{APP_NAME}', # Use a unique identifier
        'NSHumanReadableCopyright': '© 2025 Your Name, All Rights Reserved'
    },
    'argv_emulation': True,
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
